name: Django CI/CD for users
on:
  push:
    branches: [ "main", "users" ]
  pull_request:
    branches: [ "main", "users" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: 1.3.2
      POETRY_VIRTUALENVS_CREATE: "false"
      # DB
#      DB_ENGINE: "postgres"
#      DB_HOST: "postgres"
#      DB_PORT: 5432
#      DB_NAME: "postgres"
#      DB_USER: "postgres"
#      DB_PASSWORD: "postgres"
#      POSTGRES_HOST_AUTH_METHOD: "trust"
      # Django
      DJANGO_ENV: "DEVELOPMENT"
      DJANGO_LOG_LEVEL: "INFO"
      DJANGO_SECRET_KEY: "whatever"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_CORS_ALLOWED_ORIGINS: "http://localhost"
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry && cd backend/users
          poetry install
      - name: flake8
        run: | 
          cd backend/users &&
          poetry run pre-commit run --all-files
      - name: tests
        run: |
          poetry run python backend/manage.py test
