name: Django CI/CD for users
on:
  push:
    branches: [ "main", "users" ]
  pull_request:
    branches: [ "main", "users" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install flake8 black
      - name: Test with flake8
        run: |
          cd backend/users
          python -m flake8 && python -m black .
